# Generated by Django 5.1.4 on 2024-12-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.CharField(choices=[('admin', 'admin'), ('instructor', 'instructor'), ('TA', 'TA')], default='admin', max_length=10),
        ),
    ]
