# Generated by Django 5.1.4 on 2024-12-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0007_alter_course_course_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='EmailList',
        ),
        migrations.RemoveField(
            model_name='role',
            name='action_access',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_name',
        ),
        migrations.AddField(
            model_name='role',
            name='role_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True, verbose_name=10),
        ),
    ]
